// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/blocksync/stub.proto

package blocksync

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SigCountMessage is a stripped down view of Message used by the blocksync
// MsgBytesFilter for validation before unmarshalling the full BlockResponse
// Message. Only the BlockResponse oneof case is modelled, and only the path
// down to {Block,Extended}Commit.signatures.
type SigCountMessage struct {
	BlockResponse *SigCountBlockResponse `protobuf:"bytes,3,opt,name=block_response,json=blockResponse,proto3" json:"block_response,omitempty"`
}

func (m *SigCountMessage) Reset()         { *m = SigCountMessage{} }
func (m *SigCountMessage) String() string { return proto.CompactTextString(m) }
func (*SigCountMessage) ProtoMessage()    {}
func (*SigCountMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33a924f7a4c66c7, []int{0}
}
func (m *SigCountMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigCountMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigCountMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigCountMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigCountMessage.Merge(m, src)
}
func (m *SigCountMessage) XXX_Size() int {
	return m.Size()
}
func (m *SigCountMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SigCountMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SigCountMessage proto.InternalMessageInfo

func (m *SigCountMessage) GetBlockResponse() *SigCountBlockResponse {
	if m != nil {
		return m.BlockResponse
	}
	return nil
}

type SigCountBlockResponse struct {
	Block     *SigCountBlock          `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	ExtCommit *SigCountExtendedCommit `protobuf:"bytes,2,opt,name=ext_commit,json=extCommit,proto3" json:"ext_commit,omitempty"`
}

func (m *SigCountBlockResponse) Reset()         { *m = SigCountBlockResponse{} }
func (m *SigCountBlockResponse) String() string { return proto.CompactTextString(m) }
func (*SigCountBlockResponse) ProtoMessage()    {}
func (*SigCountBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33a924f7a4c66c7, []int{1}
}
func (m *SigCountBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigCountBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigCountBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigCountBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigCountBlockResponse.Merge(m, src)
}
func (m *SigCountBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *SigCountBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SigCountBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SigCountBlockResponse proto.InternalMessageInfo

func (m *SigCountBlockResponse) GetBlock() *SigCountBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *SigCountBlockResponse) GetExtCommit() *SigCountExtendedCommit {
	if m != nil {
		return m.ExtCommit
	}
	return nil
}

type SigCountBlock struct {
	LastCommit *SigCountCommit `protobuf:"bytes,4,opt,name=last_commit,json=lastCommit,proto3" json:"last_commit,omitempty"`
}

func (m *SigCountBlock) Reset()         { *m = SigCountBlock{} }
func (m *SigCountBlock) String() string { return proto.CompactTextString(m) }
func (*SigCountBlock) ProtoMessage()    {}
func (*SigCountBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33a924f7a4c66c7, []int{2}
}
func (m *SigCountBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigCountBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigCountBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigCountBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigCountBlock.Merge(m, src)
}
func (m *SigCountBlock) XXX_Size() int {
	return m.Size()
}
func (m *SigCountBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_SigCountBlock.DiscardUnknown(m)
}

var xxx_messageInfo_SigCountBlock proto.InternalMessageInfo

func (m *SigCountBlock) GetLastCommit() *SigCountCommit {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

type SigCountCommit struct {
	Signatures []NoSig `protobuf:"bytes,4,rep,name=signatures,proto3,customtype=NoSig" json:"signatures"`
}

func (m *SigCountCommit) Reset()         { *m = SigCountCommit{} }
func (m *SigCountCommit) String() string { return proto.CompactTextString(m) }
func (*SigCountCommit) ProtoMessage()    {}
func (*SigCountCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33a924f7a4c66c7, []int{3}
}
func (m *SigCountCommit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigCountCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigCountCommit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigCountCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigCountCommit.Merge(m, src)
}
func (m *SigCountCommit) XXX_Size() int {
	return m.Size()
}
func (m *SigCountCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_SigCountCommit.DiscardUnknown(m)
}

var xxx_messageInfo_SigCountCommit proto.InternalMessageInfo

type SigCountExtendedCommit struct {
	ExtendedSignatures []NoSig `protobuf:"bytes,4,rep,name=extended_signatures,json=extendedSignatures,proto3,customtype=NoSig" json:"extended_signatures"`
}

func (m *SigCountExtendedCommit) Reset()         { *m = SigCountExtendedCommit{} }
func (m *SigCountExtendedCommit) String() string { return proto.CompactTextString(m) }
func (*SigCountExtendedCommit) ProtoMessage()    {}
func (*SigCountExtendedCommit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33a924f7a4c66c7, []int{4}
}
func (m *SigCountExtendedCommit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigCountExtendedCommit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigCountExtendedCommit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigCountExtendedCommit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigCountExtendedCommit.Merge(m, src)
}
func (m *SigCountExtendedCommit) XXX_Size() int {
	return m.Size()
}
func (m *SigCountExtendedCommit) XXX_DiscardUnknown() {
	xxx_messageInfo_SigCountExtendedCommit.DiscardUnknown(m)
}

var xxx_messageInfo_SigCountExtendedCommit proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SigCountMessage)(nil), "tendermint.blocksync.SigCountMessage")
	proto.RegisterType((*SigCountBlockResponse)(nil), "tendermint.blocksync.SigCountBlockResponse")
	proto.RegisterType((*SigCountBlock)(nil), "tendermint.blocksync.SigCountBlock")
	proto.RegisterType((*SigCountCommit)(nil), "tendermint.blocksync.SigCountCommit")
	proto.RegisterType((*SigCountExtendedCommit)(nil), "tendermint.blocksync.SigCountExtendedCommit")
}

func init() { proto.RegisterFile("tendermint/blocksync/stub.proto", fileDescriptor_c33a924f7a4c66c7) }

var fileDescriptor_c33a924f7a4c66c7 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x93, 0xaf, 0xed, 0x07, 0x4e, 0x6d, 0x85, 0xb5, 0x4a, 0xf0, 0x90, 0x96, 0xe8, 0xa1,
	0xa0, 0x26, 0xa0, 0x07, 0xf1, 0xa2, 0xd0, 0xd2, 0x93, 0x28, 0x98, 0x82, 0x88, 0x97, 0x92, 0xa4,
	0x6b, 0xba, 0xd8, 0x64, 0x4b, 0x76, 0x02, 0xf5, 0x2d, 0x7c, 0x03, 0x5f, 0xa7, 0xc7, 0x1e, 0xc5,
	0x43, 0x91, 0xf6, 0x45, 0xa4, 0x9b, 0xb4, 0xb6, 0x10, 0xaa, 0xb7, 0xd9, 0x99, 0xdf, 0xef, 0x3f,
	0x7b, 0x18, 0xa8, 0x22, 0x0d, 0xbb, 0x34, 0x0a, 0x58, 0x88, 0x96, 0xdb, 0xe7, 0xde, 0x8b, 0x78,
	0x0d, 0x3d, 0x4b, 0x60, 0xec, 0x9a, 0x83, 0x88, 0x23, 0x27, 0x95, 0x1f, 0xc0, 0x5c, 0x02, 0x07,
	0x15, 0x9f, 0xfb, 0x5c, 0x02, 0xd6, 0xbc, 0x4a, 0x58, 0x83, 0xc2, 0x4e, 0x9b, 0xf9, 0x4d, 0x1e,
	0x87, 0x78, 0x4b, 0x85, 0x70, 0x7c, 0x4a, 0x6c, 0x28, 0x4b, 0xab, 0x13, 0x51, 0x31, 0xe0, 0xa1,
	0xa0, 0x5a, 0xae, 0xa6, 0xd6, 0x8b, 0x67, 0xc7, 0x66, 0x56, 0xae, 0xb9, 0xd0, 0x1b, 0xf3, 0x8e,
	0x9d, 0x2a, 0x76, 0xc9, 0x5d, 0x7d, 0x1a, 0xef, 0x2a, 0xec, 0x65, 0x82, 0xe4, 0x12, 0x0a, 0x12,
	0xd5, 0x54, 0xb9, 0xe4, 0xf0, 0x2f, 0x4b, 0x12, 0x83, 0xdc, 0x00, 0xd0, 0x21, 0x76, 0x3c, 0x1e,
	0x04, 0x0c, 0xb5, 0x7f, 0xd2, 0x3f, 0xd9, 0xec, 0xb7, 0x86, 0x72, 0xdc, 0x6d, 0x4a, 0xc7, 0xde,
	0xa2, 0x43, 0x4c, 0x4a, 0xe3, 0x01, 0x4a, 0x6b, 0x4b, 0x48, 0x0b, 0x8a, 0x7d, 0x47, 0x2c, 0xe3,
	0xf3, 0x32, 0xfe, 0x68, 0x73, 0x7c, 0x1a, 0x0b, 0x73, 0x31, 0xcd, 0xbd, 0x86, 0xf2, 0xfa, 0x94,
	0x9c, 0x02, 0x08, 0xe6, 0x87, 0x0e, 0xc6, 0x11, 0x15, 0x5a, 0xbe, 0x96, 0xab, 0x6f, 0x37, 0x4a,
	0xa3, 0x49, 0x55, 0xf9, 0x9c, 0x54, 0x0b, 0x77, 0xbc, 0xcd, 0x7c, 0x7b, 0x05, 0x30, 0x1e, 0x61,
	0x3f, 0xfb, 0xf7, 0xe4, 0x0a, 0x76, 0x69, 0xda, 0xe9, 0xfc, 0x96, 0x48, 0x16, 0x64, 0x7b, 0x09,
	0x36, 0xee, 0x47, 0x53, 0x5d, 0x1d, 0x4f, 0x75, 0xf5, 0x6b, 0xaa, 0xab, 0x6f, 0x33, 0x5d, 0x19,
	0xcf, 0x74, 0xe5, 0x63, 0xa6, 0x2b, 0x4f, 0x17, 0x3e, 0xc3, 0x5e, 0xec, 0x9a, 0x1e, 0x0f, 0x2c,
	0x74, 0xbc, 0x1e, 0x73, 0xd1, 0xb3, 0x3c, 0x1e, 0x50, 0x74, 0x9f, 0xd1, 0x4a, 0x8e, 0x28, 0xeb,
	0x0a, 0xdd, 0xff, 0x72, 0x76, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xd5, 0x22, 0xe5, 0xa4,
	0x02, 0x00, 0x00,
}

func (m *SigCountMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigCountMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigCountMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockResponse != nil {
		{
			size, err := m.BlockResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStub(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}

func (m *SigCountBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigCountBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigCountBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExtCommit != nil {
		{
			size, err := m.ExtCommit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStub(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStub(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigCountBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigCountBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigCountBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastCommit != nil {
		{
			size, err := m.LastCommit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStub(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}

func (m *SigCountCommit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigCountCommit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigCountCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for iNdEx := len(m.Signatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Signatures[iNdEx].Size()
				i -= size
				if _, err := m.Signatures[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintStub(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	return len(dAtA) - i, nil
}

func (m *SigCountExtendedCommit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigCountExtendedCommit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigCountExtendedCommit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExtendedSignatures) > 0 {
		for iNdEx := len(m.ExtendedSignatures) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.ExtendedSignatures[iNdEx].Size()
				i -= size
				if _, err := m.ExtendedSignatures[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintStub(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintStub(dAtA []byte, offset int, v uint64) int {
	offset -= sovStub(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SigCountMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockResponse != nil {
		l = m.BlockResponse.Size()
		n += 1 + l + sovStub(uint64(l))
	}
	return n
}

func (m *SigCountBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovStub(uint64(l))
	}
	if m.ExtCommit != nil {
		l = m.ExtCommit.Size()
		n += 1 + l + sovStub(uint64(l))
	}
	return n
}

func (m *SigCountBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastCommit != nil {
		l = m.LastCommit.Size()
		n += 1 + l + sovStub(uint64(l))
	}
	return n
}

func (m *SigCountCommit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Signatures) > 0 {
		for _, e := range m.Signatures {
			l = e.Size()
			n += 1 + l + sovStub(uint64(l))
		}
	}
	return n
}

func (m *SigCountExtendedCommit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ExtendedSignatures) > 0 {
		for _, e := range m.ExtendedSignatures {
			l = e.Size()
			n += 1 + l + sovStub(uint64(l))
		}
	}
	return n
}

func sovStub(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStub(x uint64) (n int) {
	return sovStub(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SigCountMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigCountMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigCountMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockResponse == nil {
				m.BlockResponse = &SigCountBlockResponse{}
			}
			if err := m.BlockResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigCountBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigCountBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigCountBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &SigCountBlock{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExtCommit == nil {
				m.ExtCommit = &SigCountExtendedCommit{}
			}
			if err := m.ExtCommit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigCountBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigCountBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigCountBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCommit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastCommit == nil {
				m.LastCommit = &SigCountCommit{}
			}
			if err := m.LastCommit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigCountCommit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigCountCommit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigCountCommit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signatures", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v NoSig
			m.Signatures = append(m.Signatures, v)
			if err := m.Signatures[len(m.Signatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigCountExtendedCommit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStub
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigCountExtendedCommit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigCountExtendedCommit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedSignatures", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStub
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthStub
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthStub
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v NoSig
			m.ExtendedSignatures = append(m.ExtendedSignatures, v)
			if err := m.ExtendedSignatures[len(m.ExtendedSignatures)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStub(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStub
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStub(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStub
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStub
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStub
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStub
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStub
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStub
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStub        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStub          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStub = fmt.Errorf("proto: unexpected end of group")
)
